export type IconName =
  | "ic_linkedin"
  | "ic_facebook"
  | "ic_github"
  | "ic_viber"
  | "ic_whatsapp"
  | "ic_javascript"
  | "ic_react"
  | "ic_vue"
  | "ic_mysql"
  | "ic_typescript"
  | "ic_redux"
  | "ic_material"
  | "ic_tailwind"
  | "ic_chakra"
  | "ic_nodejs"
  | "ic_express"
  | "ic_manOnTable";
